# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_result_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='result_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
