# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180207_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='initial_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
