# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_stock_initial_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='initial_value',
            new_name='inistock_value',
        ),
    ]
