# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-07 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180207_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='inistock_value',
            new_name='stock_value',
        ),
    ]
